[package]
name = "command-line"
version = "0.1.0"
edition = "2021"

[dependencies]
generator = { path = "../generator" }

serde = { version = "1.0.164", features = ["derive"] }
toml = "0.7.4"

pdfium-render = "0.8.5"
