[package]
name = "gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generator = { path = "../generator" }
eframe = "0.22"
env_logger = "0.10"
serde_json = "1.0"
open = "5"
